[package]
name = "fabric1"
version = "1.0.0"
authors = ["Proton64"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
rodio = "*"